eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

name:
  value: azienda

spring:
  cloud:
    config:
      override-system-properties: false