apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
    template:
      metadata:
        labels:
          app: discovery
      spec:
        containers:
          - name: discovery
            image: discovery:latest
            ports:
              - containerPort: 8761