spring:
  application:
    name: comunicazioni-service
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/comunicazioni
    username: azienda
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    producer:
      bootstrap-server: localhost:9092
      group-id: order-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.azienda.comunicazioni_aziendali.kafka.OrderConfirmation


server:
  port: 8080

application:
  config:
    dipendenti-url: http://localhost:9000/api/v1/dipendeti
    dipartimenti-url: http://localhost:8090/api/v1/dipartimenti
