spring:
  application:
    name: dipendenti-service
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dipendenti
    username: azienda
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 9000

application:
  config:
    dipartimenti-url: http://localhost:8090/api/v1/dipartimenti
    posizioni-lavorative-url: http://localhost:9020/api/v1/posizionelavorativa