name: CI Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build maven
        run: |
          cd services/config-server && mvn clean compile package -U -Djdk.compiler.disablePreview=true
          cd ../discovery && mvn clean compile package -U -Djdk.compiler.disablePreview=true
          cd ../api_gateway && mvn clean compile package -U -Djdk.compiler.disablePreview=true
          cd ../dipendenti && mvn clean compile package install -U -Djdk.compiler.disablePreview=true
          cd ../newses && mvn clean compile package install -U -Djdk.compiler.disablePreview=true
          cd ../notifications && mvn clean compile package -U -Djdk.compiler.disablePreview=true

      - name: Run tests
        run: |
          cd services/config-server && mvn test
          cd ../discovery && mvn test
          cd ../api_gateway && mvn test
          cd ../dipendenti && mvn test
          cd ../newses && mvn test
          cd ../notifications && mvn test