name: CI Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build maven
        run: |
          cd services/config-server && mvn clean compile package -U -Djdk.compiler.disablePreview=true
          cd ../discovery && mvn clean compile package -U -Djdk.compiler.disablePreview=true
          cd ../api_gataway && mvn clean compile package -U -Djdk.compiler.disablePreview=true
          cd ../dipendenti && mvn clean compile package install -U -Djdk.compiler.disablePreview=true
          cd ../newses && mvn clean compile package install -U -Djdk.compiler.disablePreview=true

      - name: Run tests
        run: |
          cd services/config-server && mvn test
          cd ../discovery && mvn test
          cd ../api_gataway && mvn test
          cd ../dipendenti && mvn test
          cd ../newses && mvn test

      - name: Build dockerimage configserver
        run: |
          cd services/config-server
          docker build -t friggitello/configserver:latest .
      - name: Build dockerimage discovery
        run: |
          cd services/discovery
          docker build -t friggitello/discovery:latest .
      - name: Build dockerimage apigateway
        run: |
          cd services/api_gataway
          docker build -t friggitello/apigataway:latest .
      - name: Build dockerimage dipendenti
        run: |
          cd services/dipendenti
          docker build -t friggitello/dipendenti:latest .
      - name: Build dockerimage newses
        run: |
          cd services/newses
          docker build -t friggitello/newses:latest .